# Use the official PostgreSQL image as the base
FROM postgres:latest

# Set the environment variables
ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD password
ENV POSTGRES_DB spotify

# Copy the custom initialization script to the container
COPY init-db.sh /docker-entrypoint-initdb.d/

# Grant permissions to the initialization script
RUN chmod +x /docker-entrypoint-initdb.d/init-db.sh
